name: Test and Build

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Optional (later when Errors are fixed)
      # - name: Lint the code
      #   run: npm run lint
      #   continue-on-error: true

      # Optional (when tests are done)
      - name: Run tests
        run: npm test

      - name: Build the app
        run: npm run build

      - name: Test Docker build
        run: docker build -t cocreate-test-build .
